import axios from 'axios'

axios.defaults.withCredentials = true;

function getData(url,methods,params) {
    if(methods=='get'){
        axios.get(url).then(res=>{
            return res;
        }).catch(error=>{
            return error;
        })
    }
    else if(methods=='post'){
        axios.post(url,params).then(res=>{
            return res;
        }).catch(error=>{
            return error;
        })
    }
    
}
export default {
    //获取右侧菜单
    getLeftMenuList(){
    var data=
        [
            {
                index:0,
                name:'每日推荐'
            },
            {
                index:1,
                name:'主题日报'
            },
            {
                index:2,
                name:'日常心理学'
            },
            {
                index:3,
                name:'用户推荐日报'
            },
            {
                index:4,
                name:'电影日报'
            },
            {
                index:5,
                name:'不许无聊'
            },
            {
                index:6,
                name:'设计日报'
            },
            {
                index:7,
                name:'大公司日报'
            },
            {
                index:8,
                name:'互联网安全'
            },
            {
                index:9,
                name:'开始游戏'
            },
            {
                index:10,
                name:'动漫日报'
            },
            {
                index:11,
                name:'音乐日报'
            },
            {
                index:12,
                name:'财经日报'
            },
            {
                index:13,
                name:'体育日报'
            },
            {
                index:14,
                name:'设计日报'
            },
        ]
        //getData('/api/service/getIpInfo.php?ip=117.89.35.51','get','');
    
        return data;
    },
    //获取右侧标题
    getRightTitle(indexMenu){
        var rightTitle;
        if(indexMenu==0){
            rightTitle=[
                {
                    index:0,
                    imgSrc:'../../assets/title/01.jpg',
                    title:'[人民致命的杀手]这话听着就像是谣言',
                    articleId:0,
                },
                {
                    index:1,
                    imgSrc:'./src/assets/title/01.jpg',
                    title:'有限责任公司的责任到底是多[责任]',
                    articleId:1,
                },
                {
                    index:2,
                    imgSrc:'../assets/title/01.jpg',
                    title:'[古墓就那么多，挖完了该怎么办]',
                    articleId:2,
                },
                {
                    index:3,
                    imgSrc:'../assets/title/01.jpg',
                    title:'脱离30年，那本书能教你认识[云]么？',
                    articleId:3,
                },
                {
                    index:4,
                    imgSrc:'../assets/title/01.jpg',
                    title:'猪那个部位最好吃，哪里不好吃？',
                    articleId:4,
                },
                {
                    index:5,
                    imgSrc:'../../assets/title/01.jpg',
                    title:'[人民致命的杀手]这话听着就像是谣言',
                    articleId:0,
                },
                {
                    index:6,
                    imgSrc:'./src/assets/title/01.jpg',
                    title:'有限责任公司的责任到底是多[责任]',
                    articleId:1,
                },
                {
                    index:7,
                    imgSrc:'../assets/title/01.jpg',
                    title:'[古墓就那么多，挖完了该怎么办]',
                    articleId:2,
                },
                {
                    index:8,
                    imgSrc:'../assets/title/01.jpg',
                    title:'脱离30年，那本书能教你认识[云]么？',
                    articleId:3,
                },
                {
                    index:9,
                    imgSrc:'../assets/title/01.jpg',
                    title:'猪那个部位最好吃，哪里不好吃？',
                    articleId:4,
                },
            ]
        }
        else if(indexMenu==1){
            rightTitle=[
                {
                    index:0,
                    imgSrc:'../assets/title/02.jpg',
                    title:'猪那个部位最好吃，哪里不好吃？',
                    articleId:4,
                },
                {
                    index:1,
                    imgSrc:'../assets/title/02.jpg',
                    title:'脱离30年，那本书能教你认识[云]么？',
                    articleId:3,
                },
                {
                    index:2,
                    imgSrc:'../assets/title/02.jpg',
                    title:'[古墓就那么多，挖完了该怎么办]',
                    articleId:2,
                },
                {
                    index:3,
                    imgSrc:'../assets/title/02.jpg',
                    title:'有限责任公司的责任到底是多[责任]',
                    articleId:1,
                },
                {
                    index:4,
                    imgSrc:'../assets/title/02.jpg',
                    title:'[人民致命的杀手]这话听着就像是谣言',
                    articleId:0,
                },
            ]
        }
        else if(indexMenu==2){
            rightTitle=[
                {
                    index:0,
                    imgSrc:'../assets/title/03.jpg',
                    title:'[人民致命的杀手]这话听着就像是谣言',
                    articleId:0,
                },
                {
                    index:1,
                    imgSrc:'../assets/title/03.jpg',
                    title:'有限责任公司的责任到底是多[责任]',
                    articleId:1,
                },
                {
                    index:2,
                    imgSrc:'../assets/title/03.jpg',
                    title:'[古墓就那么多，挖完了该怎么办]',
                    articleId:2,
                },
                {
                    index:3,
                    imgSrc:'../assets/title/03.jpg',
                    title:'脱离30年，那本书能教你认识[云]么？',
                    articleId:3,
                },
                {
                    index:4,
                    imgSrc:'../assets/title/03.jpg',
                    title:'猪那个部位最好吃，哪里不好吃？',
                    articleId:4,
                },
            ]
        }
        else if(indexMenu==3){
            rightTitle=[
                {
                    index:0,
                    imgSrc:'../assets/title/04.jpg',
                    title:'猪那个部位最好吃，哪里不好吃？',
                    articleId:4,
                },
                {
                    index:1,
                    imgSrc:'../assets/title/04.jpg',
                    title:'脱离30年，那本书能教你认识[云]么？',
                    articleId:3,
                },
                {
                    index:2,
                    imgSrc:'../assets/title/04.jpg',
                    title:'[古墓就那么多，挖完了该怎么办]',
                    articleId:2,
                },
                {
                    index:3,
                    imgSrc:'../assets/title/04.jpg',
                    title:'有限责任公司的责任到底是多[责任]',
                    articleId:1,
                },
                {
                    index:4,
                    imgSrc:'../assets/title/04.jpg',
                    title:'[人民致命的杀手]这话听着就像是谣言',
                    articleId:0,
                },
            ]
        }
        else if(indexMenu==4){
            rightTitle=[
                {
                    index:0,
                    imgSrc:'../assets/title/05.jpg',
                    title:'[人民致命的杀手]这话听着就像是谣言',
                },
                {
                    index:1,
                    imgSrc:'../assets/title/05.jpg',
                    title:'有限责任公司的责任到底是多[责任]',
                },
                {
                    index:2,
                    imgSrc:'../assets/title/05.jpg',
                    title:'[古墓就那么多，挖完了该怎么办]',
                },
                {
                    index:3,
                    imgSrc:'../assets/title/05.jpg',
                    title:'脱离30年，那本书能教你认识[云]么？',
                },
                {
                    index:4,
                    imgSrc:'../assets/title/05.jpg',
                    title:'猪那个部位最好吃，哪里不好吃？',
                },
            ]
        }
        //getData('','post',indexMenu);
        return rightTitle;
    }
}
